# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20160516_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
