# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20160516_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='borrow',
        ),
        migrations.RemoveField(
            model_name='logfile',
            name='total_book',
        ),
        migrations.AddField(
            model_name='logfile',
            name='return_status',
            field=models.BooleanField(default=0),
        ),
    ]
